# Site settings
title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Theme settings
subtitle:     "Subtitle"
cover_image:  blog-cover.jpg
logo:         logo.png

# Company information
company:      Incorporated
facebook:     facebook
twitter:      twitter
gplus:        '111'
about_link:   /about/

# Product Information
product_link: http://google.com/
tagline:      "Tagline"

# Comments
disqus:
# Eg. "exampleblog" Set to false to disable comments
shortname:  false

# Sharing settings
sharing:
twitter:    false
facebook:   false
gplus:      false
hn:         false

# Pagination
paginate: 10

# Build settings
markdown: kramdown
permalink: pretty
