# Site settings
title: Premise Blog
email: contact@premise.com
description: "Updates and news from Premise."
baseurl: ""
url: "http://blog.premise.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
