# Site settings
title: Premise Blog
email: contact@premise.com
description: "Updates and news from Premise."
baseurl: ""
url: "http://blog.premise.com"
twitter_username: premisedata


# Theme settings
subtitle:     "Product news, stories, and occasional updates."
cover_image:  blog-cover.jpg
logo:         logo.png

# Company information
company:      Premise
facebook:     premisedata
twitter:      premisedata
about_link:   /about/

# Product Information
product_link: http://google.com/
tagline:      "Tagline"

# Comments
disqus:
# Eg. "exampleblog" Set to false to disable comments
shortname:  false

# Sharing settings
sharing:
  twitter:    true
  facebook:   true
  gplus:      true
  hn:         true

# Pagination
paginate: 10

# Build settings
markdown: kramdown
permalink: pretty
